apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fc-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fc-api
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70