
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fc-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fc-api-rb
subjects:
  - kind: ServiceAccount
    name: fc-api
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io